### PR TITLE
Fix Postgres backups

### LINKED ISSUE #23: Postgres STARTER_HOST seems to be deprecated
The `Client::STARTER_HOST` (`https://postgres-starter-api.heroku.com`) and refuses connections with an SSL error.
I've had to monkey patch this gem locally to replace the value of Client::STARTER_HOST with Client::PRO_HOST to keep things working

Monkey Patch I've added to my rails app:
```ruby
# frozen_string_literal: true

# Fix for Heroku API connection issues.
#
# The heroku-api-postgres gem defaults to using postgres-starter-api.heroku.com
# for API requests, but this endpoint no longer responds (Heroku deprecated
# their starter tier databases). This patch changes the default to use
# postgres-api.heroku.com which works for all database plans.

Rails.application.config.after_initialize do
  if defined?(Heroku::Api::Postgres::Client)
    Heroku::Api::Postgres::Client.send(
      :remove_const,
      :STARTER_HOST
    )
    Heroku::Api::Postgres::Client.const_set(
      :STARTER_HOST,
      Heroku::Api::Postgres::Client::PRO_HOST
    )
  end
end
```

Before adding monkey patch:
```ruby
postgres = Heroku::Api::Postgres.connect_oauth(<my_token>)
postgres.databases.info(<my_app_id>, <my_db_id>)
#=> :2:in '<main>': SSL_connect returned=1 errno=0 peeraddr=23.20.163.54:443 state=error: unexpected eof while reading (OpenSSL::SSL::SSLError)

```

After adding monkey patch:
```ruby
postgres = Heroku::Api::Postgres.connect_oauth(<my_token>)
postgres.databases.info(<my_app_id>, <my_db_id>)
#=> { valid_response... }
```

### PR DESCRIPTION
**Pull request by hunchr**
Closes #23

### CODE REVIEW

**Comment by sislr** [comment]
closes https://github.com/coorasse/heroku-api-postgres/issues/23

File: lib/heroku/api/postgres/backups.rb [hunk 1]
```diff
@@ -23,22 +23,22 @@ def info(app_id, backup_id)
           @client.perform_get_request("/client/v11/apps/#{app_id}/transfers/#{backup_id}")
         end
 
-        def schedules(app_id, database_id)
+        def schedules(database_id)
           @client.perform_get_request("/client/v11/databases/#{database_id}/transfer-schedules",
-                                      host: db_host(app_id, database_id))
+                                      host: @client.api_host)
```
Comment (sislr) [inline lib/heroku/api/postgres/backups.rb]: do we need to pass the host all the time? I think this could be assumed

File: lib/heroku/api/postgres/backups.rb [hunk 2]
```diff
@@ -23,22 +23,22 @@ def info(app_id, backup_id)
           @client.perform_get_request("/client/v11/apps/#{app_id}/transfers/#{backup_id}")
         end
 
-        def schedules(app_id, database_id)
+        def schedules(database_id)
```
Comment (sislr) [inline lib/heroku/api/postgres/backups.rb:26]: we're changing the interface here causing a breaking change. We could also go with the following to not cause a breaking change
```ruby
def schedules(_app_id, database_id)
```

Comment (hunchr) [reply lib/heroku/api/postgres/backups.rb:26]: Yes, that's a breaking change, but otherwise it would look like this `backups.schedules(nil, database_id)`

Comment (sislr) [reply lib/heroku/api/postgres/backups.rb:26]: I'd do something like the following.
```ruby
def schedules(app_id = nil, database_id)
  deprecate("Passing 'app_id' is deprecated") if app_id
  # ...
end
```

@coorasse what do you think?

Comment (hunchr) [reply lib/heroku/api/postgres/backups.rb:26]: Then you still have to pass `nil`. You probably mean this:
```rb
def schedules(*args)
  deprecate("Passing 'app_id' is deprecated") if args.length > 1

  database_id = args.last
  # ...
end
```

Comment (hunchr) [reply lib/heroku/api/postgres/backups.rb:26]: The gem is still beta (0.14.0). I think breaking changes are to be expected.

**Comment by coorasse** [comment]
ok. agree. let's have a breaking change. update the version accordingly, and mention it in the readme. cc @jai-x

**Comment by jai-x** [comment]
I think it's worth creating a minor release that keeps the current method signatures and the host selection code just always returns the pro host. This is so current users can upgrade and have the error fixed without having to make a lot of changes.

Then these larger breaking changes can be released in new a major release.

File: lib/heroku/api/postgres/backups.rb [hunk 3]
```diff
@@ -23,22 +23,19 @@ def info(app_id, backup_id)
...
 
-        def schedules(app_id, database_id)
-          @client.perform_get_request("/client/v11/databases/#{database_id}/transfer-schedules",
-                                      host: db_host(app_id, database_id))
+        def schedules(database_id)
+          @client.perform_get_request("/client/v11/databases/#{database_id}/transfer-schedules")
         end
 
-        def schedule(app_id, database_id, hour: 0o0, timezone: 'UTC')
+        def schedule(database_id, hour: 0, timezone: 'UTC')
```
Comment (coorasse) [inline lib/heroku/api/postgres/backups.rb:30]: why did the default value of `hour` change?

File: CHANGELOG.md [hunk 4]
```diff
@@ -1,16 +1,21 @@
+## 0.14.0
+
+* [#24](https://github.com/coorasse/heroku-api-postgres/pull/24): **Breaking change**: Remove `app_id` for some methods ([@hunchr])
```
Comment (coorasse) [inline CHANGELOG.md]: please explain what public methods changed signature, so it's easier to update

File: CHANGELOG.md [hunk 5]
```diff
@@ -1,16 +1,21 @@
...
 ## 0.12.0
 
-* [#18](https://github.com/coorasse/heroku-api-postgres/pull/18): Support ruby 3.0. ([@louism517][])
-* [#15](https://github.com/coorasse/heroku-api-postgres/pull/15): Return latest backup if backup_num is not provided. ([@deepakmahakale][])
-* [#14](https://github.com/coorasse/heroku-api-postgres/pull/14): Add support for rotating credentials. ([@avokhmin][])
-* [#13](https://github.com/coorasse/heroku-api-postgres/pull/13): Allow to use hour and timezone when scheduling backups. ([@avokhmin][])
+* [#18](https://github.com/coorasse/heroku-api-postgres/pull/18): Support Ruby 3.0. ([@louism517])
+* [#15](https://github.com/coorasse/heroku-api-postgres/pull/15): Return latest backup if backup_num is not provided. ([@deepakmahakale])
+* [#14](https://github.com/coorasse/heroku-api-postgres/pull/14): Add support for rotating credentials. ([@avokhmin])
+* [#13](https://github.com/coorasse/heroku-api-postgres/pull/13): Allow to use hour and timezone when scheduling backups. ([@avokhmin])
```
Comment (coorasse) [inline CHANGELOG.md]: don't touch unrelated lines in this PR please

**Review by coorasse — COMMENTED** [review]
I'd like to not touch unrelated lines and I am doubtful about the changed default value of `hour`. I remember it being explicitly the previous value for some reason.

File: lib/heroku/api/postgres/backups.rb (hunk 3 above)
Comment (hunchr) [reply lib/heroku/api/postgres/backups.rb:30]: You used `00` in [f3f4546a2](https://github.com/coorasse/heroku-api-postgres/commit/f3f4546a2cec49e2cb07d3da3ab7c04bb2a7ed63#diff-76cd5708ec9b2bb82fad6c1c460c83e2b544425295b98216dad541da86c3ecfdR25) and later RuboCop corrected it to `0o0`, but it's the same as `0`.

**Review by coorasse — APPROVED** [review]
Thanks
